[tool.poetry]
name = "newlk-search"
version = "0.1.0"
description = "Helpful package to search for TESS/Kepler/K2 data"
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
astropy = "^5.3.4"
astroquery = "^0.4.7"
joblib = "^1.3.2"
lightkurve = "^2.4.2"
numpy = "^1.26.4"
pandas = "^2.2.2"
pytest = "^7.4.4"
Requests = "^2.31.0"
rich = "^13.7.1"
sphinx_astropy = "^1.9.1"
tesswcs = "^1.1.2"
boto3 = "^1.34.25"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
