name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.11' # The pandoc version to download (if necessary) and use.
      - run: echo "# Test" | pandoc -t html
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with dev
      - name: Sphinx build
        run: |
          poetry run sphinx-build docs _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
